# Generated by Django 2.2.16 on 2021-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20211223_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
    ]
